//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Face2Face.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventTable()
        {
            this.MessageTable = new HashSet<MessageTable>();
            this.ReviewTable = new HashSet<ReviewTable>();
            this.UserProfile1 = new HashSet<UserProfile>();
        }
    
        public int EventID { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
        public System.DateTime Date { get; set; }
        public string Summary { get; set; }
        public Nullable<System.DateTime> EndSignUpDate { get; set; }
        public Nullable<int> MaxUsers { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public string Address { get; set; }
    
        public virtual LanguagesTable LanguagesTable { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageTable> MessageTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewTable> ReviewTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfile1 { get; set; }
    }
}
