//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Face2Face.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportTable
    {
        public int ReviewID { get; set; }
        public int UserID { get; set; }
        public string ReportType { get; set; }
    
        public virtual ReviewTable ReviewTable { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
